### ISSUE TITLE
Должен быть номер карты (мой и адресата) и сумма, а не id

### ISSUE THREAD

**Issue by coursar** [Veliall/web#11]
https://github.com/Veliall/web/blob/6171a7e78ef89a7a1961f7f40e7b547c0c70837f/src/main/java/org/example/app/dto/TransferRequestDto.java#L12

**Comment by Veliall** [comment]
Адресата сделал по номеру карты. А свою  по Айди , потому что хотелось в адресной строке оставить именно Айдишник , а не прямо номер карты. В моём представлении пользователь выбирает карту , переходит на её страницу и уже дальше выбирает кому перевести по номеру карты адресата. 
Но если необходимо - переделать тоже не трудно.
